init:
  - git config --global core.autocrlf input

os: Visual Studio 2015

build_script:
  - build.cmd /v:normal

# we run the tests ourselves in build.proj for coverage
test: off

deploy:
  - provider: NuGet
    api_key:
      secure: 7MS5+XWaFchMXFqzgneQCqo9U0DlxiPXe/KWWUnbCBDEizVn06EjdQZkWu1gbNOJ
    artifact: /.*\.nupkg/
    on:
      branch: master
      
nuget:
  project_feed: true
  disable_publish_on_pr: true
  
artifacts:
  - path: '*.nupkg'
    name: Packages